name: Build Typst document
on: [push]
permissions:
  contents: write
jobs:
  build_typst:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Typst
        uses: typst-community/setup-typst@v4
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        uses: ammar-ahmed22/compile-typst-action@v1
        with:
          source_paths: 'main.typ'
          output_paths: 'malalengua.pdf'
          fonts_path: ''
      - name: Upload
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          name: PDF
          path: '**/*.pdf'